### ISSUE TITLE
WorkflowRunner.addTask() does not accept 'unlimited' for memMb attribute

### ISSUE THREAD

**Issue by hyjkim** [ctsa/pyflow#4]
By default, workflows have an 'unlimited' amount of Mb associated with each job. This is a problem when trying to add a new task and passing in self.getMemMb() as the value for memMb.

addTask() should check that the value is 'unlimited' if the default value is not an integer instead of throwing an exception.

**Comment by ctsa** [comment]
The memMb argument to addTask is never supposed to be unlimited, so the exception seems sensible, the self.getMemMb() represents the pool of memory available to all tasks on a local server -- are you trying to launch a task in such a way to ensure that no other task will run on the server at the same time?


I'll walk through the memory handling policy and see if this helps pinpoint where the problem you're encountering is:

The API page might be helpful:
http://ctsa.github.io/pyflow/WorkflowRunner_API_html_doc/index.html

You can specify memMb in two places, on the `workflow.run()` command and `addTask()`. In the `workflow.run()` method, memMb is intended to represent the total memory available on the host server when running in 'local' mode. The concept really doesn't make any sense on SGE, so we default to 'unlimited' which essentially tells pyflow to ignore this resource constraint. Not that we attempt to communicate task memory requirements to SGE but this is not completely standardized. Here is the documentation for memMb on the run method:

- memMb - Total memory available (in megabytes), or 'unlimited', Note that this value will be ignored in non-local modes (such as sge), because in this case total memory available is expected to be known by the scheduler for each node in its cluster. (default: 2048*nCores for local mode, 'unlimited' for sge mode)

The other time this value is set is in the `addTask()` call. This is intended to represent the maximum memory used by a task. This value is used to control the number of tasks launched on a local server to prevent paging or we attempt to pass this information on the SGE scheduler. This is the documentation of `addTask()` memMb:

- memMb - Amount of memory required (in megabytes)

This value defaults to 2048.

**Comment by hyjkim** [comment]
I see. Looking at the source of siteconfig.py, it appeared that memmb was being passed to the getfullcmd

**Comment by hyjkim** [comment]
@classmethod
    def qsubResourceArg(cls, nCores, memMb) :
        """
        When a task is launched using qsub in sge mode, it will call this
        function to specify the requested number of threads and megabytes
        of memory. The returned argument list will be appended to the qsub
        arguments.
        nCores -- number of threads requested
        memMb -- memory requested (in megabytes)
        """
        nCores = int(nCores)
        memMb = int(memMb)
        return cls._qsubResourceArgConfig(nCores, memMb)

    @classmethod
    def _qsubResourceArgConfig(cls, nCores, memMb) :
        """
        The default function is designed for maximum
        portability  -- it just provides more memory
        via more threads.
        """

        # this is the memory we assume is available per
        # thread on the cluster:
        #
        class Constants(object) : megsPerCore = 4096

        memCores = 1 + ((memMb - 1) / Constants.megsPerCore)

        qsubCores = max(nCores, memCores)

        if qsubCores <= 1 : return []
        return ["-pe", "threaded", str(qsubCores)]

**Comment by hyjkim** [comment]
Based on the code, it seemed the memmb was sometimes being used to specify the number or cores to reserve in sge.

I didn't check upstream to see if the memmb argument was not being passed to the qsub command, so my apologies if I incorrectly interpreted the code.

Apologies for the multiple comments. Trying to do this on mobile.

**Comment by hyjkim** [comment]
Ok, after rereading your comment, the behavior makes sense. I got caught up on the variable name rather than critically reading the documentation. Thanks for the help!
